spring.application.name=crypto-price-simulator

# Log levels
logging.level.root=INFO
logging.level.com.infina.cryptopricesimulator=DEBUG

# Console log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# Sort endpoints by controller order
springdoc.swagger-ui.operationsSorter=alpha

# Default expand depth for DTO schemas
springdoc.swagger-ui.defaultModelsExpandDepth=1

# Raw JSON URL for Swagger docs
springdoc.api-docs.path=/api-docs