spring.application.name=crypto-price-simulator

# Log seviyeleri
logging.level.root=INFO
logging.level.com.infina.cryptopricesimulator=DEBUG

# Console log formatÄ±
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n



# Swagger UI yolu (Taray?c?dan do?rudan kolayca eri?mek için)
springdoc.swagger-ui.path=/swagger-ui.html

# Endpoint'leri HTTP metotlar?na göre de?il, bizim yazd???m?z controller s?ralamas?na göre dizer
springdoc.swagger-ui.operationsSorter=alpha

# ?emalar? (DTO modellerini) varsay?lan olarak kaç katman derinlikte gösterece?ini belirler
springdoc.swagger-ui.defaultModelsExpandDepth=1

# Swagger döküman?n?n arka plandaki ham JSON url adresi
springdoc.api-docs.path=/api-docs