spring.application.name=crypto-price-simulator

# Log seviyeleri
logging.level.root=INFO
logging.level.com.infina.cryptopricesimulator=DEBUG

# Console log formatı
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n